import { useState } from 'react';
import axios from 'axios';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Form = (props) => (
  <form onSubmit={props.handleSubmit}>
    拡張機能：
    <input type='text' value={props.name} onChange={props.handleChangeName} />
    説明：
    <input type='text' value={props.desc} onChange={props.handleChangeDesc} />
    <input
      type='submit'
      value='追加'
      disabled={props.name && props.desc ? false : true}
    />
  </form>
);

const List = (props) => (
  <ul>
    {props.items.map((item) => (
      <li key={item.id}>
        {item.name} ({item.desc}) [{item.id}]
        <button onClick={() => props.handleDeleteButton(item.id)}>削除</button>
      </li>
    ))}
  </ul>
);

const Home = ({ data }) => {
  const [name, setName] = useState('');
  const [desc, setDesc] = useState('');
  const [extensions, setExtensions] = useState(data);

  const handleChangeName = (e) => {
    setName(e.target.value);
  };

  const handleChangeDesc = (e) => {
    setDesc(e.target.value);
  };

  const handleSubmit = async (e) => {
    const url = 'http://localhost:8080/';
    const extension = { name: name, desc: desc };
    await axios.post(url, extension).then((res) => {
      console.log(res);
    });
    setName('');
    setDesc('');
    e.preventDefault();
  };

  const handleDeleteButton = async (id) => {
    console.log(id);
    const url = 'http://localhost:8080/';
    const extension = { id: id };
    console.log(extension);
    await axios.delete(url, { data: extension }).then((res) => {
      console.log(res);
    });
    location.reload();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Extension Manager</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Extension Manager</h1>

        <Form
          handleSubmit={handleSubmit}
          name={name}
          handleChangeName={handleChangeName}
          desc={desc}
          handleChangeDesc={handleChangeDesc}
        />

        <List items={extensions} handleDeleteButton={handleDeleteButton} />
      </main>
    </div>
  );
};

export async function getStaticProps() {
  const url = 'http://localhost:8080/';
  const data = await axios.get(url).then((res) => {
    return res.data;
  });
  return {
    props: {
      data,
    },
  };
}

export default Home;
